### ISSUE TITLE
Error Launching Davinci wizard

### ISSUE THREAD

**Issue by fredcanfly** [H3rz3n/How-install-DaVinci-Resolve-in-Fedora-Linux#1]
I'm sorry for the vague title, but this is all it gave me.  I'm on Nobara 40. Steps I took:
1. Download the zip file, try to run it on my own, it fails telling me a file is missing, but not which one.
2. Redownload and retry with same results.
3. Find this github, download helper, run it.
4. Go to "Install missing dependencies", it runs the check and says everything is installed.
5. Go to "Launch DaVinci Resolve installer", click start.
6. It spins for a bit, then comes back saying there was an error.  I click show logs.
7. Here is the text from the log file:
```
DEBUG : There was an error launching the DaVinci Resolve installation wizard :


Please open an issue report and paste this error code on the project GitHub page :

https://github.com/H3rz3n/davinci-helper/issues
```
Screenshot is attached for further investigation.  I may also reach out to Black Magic to see if they have any suggestions.
Let me know if there is any other info you need.  I suspect the issue is either with Davinci or Nobara, but I am trying all avenues here.

![Screenshot_20241027_233149](https://github.com/user-attachments/assets/6d8d5e29-c951-4ca0-8b37-6e1aa0d7f558)

**Comment by H3rz3n** [comment]
Hi, I'm Lorenzo, the developer of DaVinci Helper, thank you for installing it. The problem your're reporting it's a very strange issue.

 Can you please tell me what version of DaVinci are you trying to exec ?

Can you please try to start manually the DaVinci Resole .run installer using the following commands and then paste here the ouput ?

Steps to start DaVinci Resolve .run :

- Open the folder containing the .run file.
- Be sure there in only one .run file inside the folder
- Start a new terminal inside this folder using "right click on an article empty space, start a new terminal window".
- Paste and exec this command : `SKIP_PACKAGE_CHECK=1 ./*.run`
- Paste there the terminal output.

Thank you for pointig me that out !
